package com.shermant.core.model

enum class LucideIconCategory(
    val displayName: String,
) {
    Accessibility("Accessibility"),
    Account("Account"),
    Animals("Animals"),
    Arrows("Arrows"),
    Buildings("Buildings"),
    Charts("Charts"),
    Communication("Communication"),
    Connectivity("Connectivity"),
    Cursors("Cursors"),
    Design("Design"),
    Development("Development"),
    Devices("Devices"),
    Emoji("Emoji"),
    Files("Files"),
    Finance("Finance"),
    FoodBeverage("Food Beverage"),
    Gaming("Gaming"),
    Home("Home"),
    Layout("Layout"),
    Mail("Mail"),
    Math("Math"),
    Medical("Medical"),
    Multimedia("Multimedia"),
    Nature("Nature"),
    Navigation("Navigation"),
    Notifications("Notifications"),
    People("People"),
    Photography("Photography"),
    Science("Science"),
    Seasons("Seasons"),
    Security("Security"),
    Shapes("Shapes"),
    Shopping("Shopping"),
    Social("Social"),
    Sports("Sports"),
    Sustainability("Sustainability"),
    Text("Text"),
    Time("Time"),
    Tools("Tools"),
    Transportation("Transportation"),
    Travel("Travel"),
    Weather("Weather"),
    Custom("Custom"),
}
