name: Local Maven Publish via act

on:
  workflow_dispatch:

jobs:
  local-publish:
    runs-on: ubuntu-latest
    env:
      ACT: "true"
      MAVEN_REPOSITORY_URL: file://${{ github.workspace }}/build/test-maven-repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: "23"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.4

      - name: Publish libraries to file Maven repository
        run: bash ./gradlew publish -PlocalPublish=true
